AZURE_ENDPOINT=https://ai-vision-learn-002.cognitiveservices.azure.com/
AZURE_KEY=1S9pkDMbFl7Qc51Wz6IFJ4NyoW1XKuQqF2Qtrh28CYFTWLRxJnUaJQQJ99CAACYeBjFXJ3w3AAAFACOGpPB4
IMAGE_URL=https://your-storage.blob.core.windows.net/images/your-image.png?sp=r&...